### ISSUE TITLE
Role CRUD

### ISSUE THREAD

**Issue by daenuli** [pondokinformatika/laravelblog#3]
Content for this menu are convenient with role_table_migration

**Comment by daenuli** [comment]
@AbidKhairyAK untuk issue ini boleh dikerjakan tanpa harus menunggu issue nya @abdurrahman88 selesai. Asalkan tidak membuat menu role. Sementara untuk aksesnya diketik manual saja via URL.

**Comment by AbidKhairyAK** [comment]
siap ustadz
