### ISSUE TITLE
Add status column on article menu

### ISSUE THREAD

**Issue by daenuli** [pondokinformatika/laravelblog#8]
Separate date and status. Move status ( published or drafted ) to status column.

**Comment by masebilal07** [comment]
Assalamualaikum ust nuli
yang ini memisahkan status dari tanggal kan ya, apa di bikin field baru di table postnya ?

syukran

**Comment by daenuli** [comment]
waalaikumsalam @masebilal07 
Iya pisahkan dari tanggal, nggak perlu tambah field baru di table. kan sudah ada. tinggal pisahkan saja ditampilannya.
Sebelum mengerjakan yang ini, checkout dulu ke master, terus pull origin master, setelah itu bikin branch baru.

**Comment by masebilal07** [comment]
oke
