### ISSUE TITLE
Enable "Contact" menu on frontend navbar

### ISSUE THREAD

**Issue by AbidKhairyAK** [pondokinformatika/laravelblog#89]
Aktifkan menu "Contact" pada navbar / header frontend

**Comment by AbidKhairyAK** [comment]
Buat Migration untuk table "contact", dengan table sebagai berikut:

- id
- nama
- email
- nomor hp
- alamat
- sosial media (ngambil dari punya ammar)

**Comment by daenuli** [comment]
target selesai 25 Sep
